apiVersion: v1
kind: Pod
metadata:
  labels:
    app: stress
  name: stress
spec:
  containers:
  - command:
    - stress \
    - --cpu 1 \
    - --io 1 \
    - --vm 1 \
    - --vm-bytes 128M \
    - --timeout 1s \
    - --verbose
    image: polinux/stress
    name: stress
  restartPolicy: Never
